name: Job

on:
  workflow_dispatch:
  push:
    branches:
      - main  

permissions:
  contents: write

jobs:
  job-step:
    name: Job
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: validate step
        id: validacao
        run: |
          git fetch
          git checkout main
          currentstep=$(cat .github/CONFIG/step.txt)
          echo "::set-output name=currentstep::$currentstep"

          chmod +x .github/CONFIG/validar.sh

          if .github/CONFIG/validar.sh "branches:" .github/workflows/meu-workflow.yml
          then
            echo "::set-output name=validar::0"
          else
            echo "::set-output name=validar::1"
          fi


      - name: Create an issue
        if: ${{ steps.validacao.outputs.currentstep == '2' && steps.validacao.outputs.validar == '0' }} 
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.ISSUE_SECRET }}
          title: Já sabemos quando o Workflow será executado!
          body: |
            ## É isso ai!!!

            Estamos cada vez mais perto de criarmos um workflow funcional.
            No passo anterior, você incluiu uma trigger, agora vamos falar um pouco sobre um Job.

            Dentro do nosso Workflow, nós temos ao menos um Job, mas podemos ter vários outros caso necessário.
            Um Job, é basicamente um **agrupamento** de passos, que serão necessários para a execução do nosso fluxo.

            Esse job, também pode ser atrelado a um _environment_, mas nós vamos ver isso com mais detalhe em outro desafio.

            Vamos então adicionar um Job ao nosso workflow?

            Inclua o seguinte bloco de código ao seu workflow:
            ```
            jobs:
              job-sample:
                name: Sample
            ```
            Pode salvar, realizar o commit e enviar para o servidor.

            Te vejo na proxima parte!
             
            ![mona-the-rivetertocat](https://octodex.github.com/images/vinyltocat.png)

      - name: Update Step
        if: ${{ steps.validacao.outputs.currentstep == '2' }}      
        run: |
          git fetch
          git checkout main
          echo "3" > .github/CONFIG/step.txt
          git config --global user.name 'Julio Arruda'
          git config --global user.email 'julio.arruda@outlook.com'          
          git add .
          git commit -m "Atualizando Step"
          git push