name: Meu Workflow

on:
 workflow_dispatch:
 push:
    branches:
      - main  


jobs:
  job-sample:
    name: Sample
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 